language: php
php:
  - '7.2.0'

services:
  - mysql

install:
  - composer install

before_script:
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:update

script:
  - bin/phpunit